name: fastlist
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  flutter_lints: ^2.0.2
  flutter_slidable: ^0.6.0
  provider: ^6.0.2
  intl: ^0.17.0
  fl_chart: ^0.40.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  bdd_widget_test: ^1.2.1
  build_runner: ^2.3.3
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/